<?php
    $title = $this->title . ' Tipo Produto';
    $this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'application',
        [
            'action' => 'save',
            'controller' => 'tipoProduto'
        ]));
    
    $form->prepare();
?>
<div class="form-group">
    <?php 
        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('id'));
        echo $this->formRow($form->get('descricao'));
    ?>
</div>

<?php 
    echo $this->formRow($form->get('submit'));
    echo $this->form()->closeTag();
?>
