<?php
    $title = 'Login';
    $this->headTitle($title);
?>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <br><br>
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Login</h1>
                    </div>
                    <form name="login" class="user" action="login/autenticacao" method="post" >
                        <div class="form-group">
                            <input type="text" class="form-control" required="" name='login' placeholder="Login">
                        </div>
                        <div class="form-group">
                            <input type="password"  class="form-control" required="" name='senha' placeholder="Senha">
                        </div>
                        <input type="submit" name="submit"  value="Entrar"  class="btn btn-primary btn-block">
                    </form>      
                </div>
            </div>
        </div>
    </div>
</div>