<p>
    <a class="btn btn-primary btn-block" href="<?=$this->url(
        'application',
        array(
            'controller'=>'cliente'
        )
    )?>">Clientes</a>
</p>

<p>
    <a class="btn btn-primary btn-block" href="<?=$this->url(
        'application',
        array(
            'controller'=>'produto'
        )
    )?>">Produtos</a>
</p>

<p>
    <a class="btn btn-primary btn-block" href="<?=$this->url(
        'application',
        array(
            'controller'=>'tipoProduto'
        )
    )?>">Tipos Produto</a>
</p>

<p>
    <a class="btn btn-primary btn-block" href="<?=$this->url(
        'application',
        array(
            'controller'=>'usuario'
        )
    )?>">Usuários</a>
</p>